/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Faculdade
 */
public class TelaAlunoCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlunoCadastro
     */
    public TelaAlunoCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeAlu = new javax.swing.JLabel();
        jLabelDataAlu = new javax.swing.JLabel();
        jLabelTelefoneAlu = new javax.swing.JLabel();
        jLabelCPFAlu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldDataAlu = new javax.swing.JTextField();
        jTextFieldNomeAlu = new javax.swing.JTextField();
        jTextFieldTelefoneAlu = new javax.swing.JTextField();
        jTextFieldCPFAlu = new javax.swing.JTextField();
        jCheckBoxAdicionarResp = new javax.swing.JCheckBox();
        jLabelNomeResp = new javax.swing.JLabel();
        jTextFieldNomeResp = new javax.swing.JTextField();
        jLabelTelefoneResp = new javax.swing.JLabel();
        jTextFieldTelefoneResp = new javax.swing.JTextField();
        jLabelDataResp = new javax.swing.JLabel();
        jTextFieldDataResp = new javax.swing.JTextField();
        jLabelCPFResp = new javax.swing.JLabel();
        jTextFieldCPFResp = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelComplemento = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jToggleButtonVoltar = new javax.swing.JToggleButton();
        jToggleButtonSalvar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNomeAlu.setText("Nome:");
        getContentPane().add(jLabelNomeAlu);
        jLabelNomeAlu.setBounds(10, 80, 50, 30);

        jLabelDataAlu.setText("Data de Nascimento:");
        getContentPane().add(jLabelDataAlu);
        jLabelDataAlu.setBounds(10, 160, 120, 30);

        jLabelTelefoneAlu.setText("Telefone:");
        getContentPane().add(jLabelTelefoneAlu);
        jLabelTelefoneAlu.setBounds(10, 120, 60, 30);

        jLabelCPFAlu.setText("CPF:");
        getContentPane().add(jLabelCPFAlu);
        jLabelCPFAlu.setBounds(230, 120, 60, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 210, 400, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 200, 400, 30);

        jTextFieldDataAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataAluActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDataAlu);
        jTextFieldDataAlu.setBounds(130, 160, 130, 30);

        jTextFieldNomeAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeAluActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeAlu);
        jTextFieldNomeAlu.setBounds(60, 80, 320, 30);

        jTextFieldTelefoneAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneAluActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefoneAlu);
        jTextFieldTelefoneAlu.setBounds(60, 120, 160, 30);

        jTextFieldCPFAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFAluActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPFAlu);
        jTextFieldCPFAlu.setBounds(260, 120, 120, 30);

        jCheckBoxAdicionarResp.setText("Adicionar Responsável");
        getContentPane().add(jCheckBoxAdicionarResp);
        jCheckBoxAdicionarResp.setBounds(10, 220, 180, 23);

        jLabelNomeResp.setText("Nome:");
        getContentPane().add(jLabelNomeResp);
        jLabelNomeResp.setBounds(10, 250, 50, 30);

        jTextFieldNomeResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeRespActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeResp);
        jTextFieldNomeResp.setBounds(60, 250, 320, 30);

        jLabelTelefoneResp.setText("Telefone:");
        getContentPane().add(jLabelTelefoneResp);
        jLabelTelefoneResp.setBounds(10, 290, 60, 30);

        jTextFieldTelefoneResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneRespActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefoneResp);
        jTextFieldTelefoneResp.setBounds(60, 290, 160, 30);

        jLabelDataResp.setText("Data de Nascimento:");
        getContentPane().add(jLabelDataResp);
        jLabelDataResp.setBounds(10, 330, 120, 30);

        jTextFieldDataResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataRespActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDataResp);
        jTextFieldDataResp.setBounds(130, 330, 130, 30);

        jLabelCPFResp.setText("CPF:");
        getContentPane().add(jLabelCPFResp);
        jLabelCPFResp.setBounds(230, 290, 60, 30);

        jTextFieldCPFResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFRespActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPFResp);
        jTextFieldCPFResp.setBounds(260, 290, 120, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 370, 400, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 380, 400, 20);

        jLabelEndereco.setText("Endereço:");
        getContentPane().add(jLabelEndereco);
        jLabelEndereco.setBounds(10, 400, 70, 30);

        jLabelComplemento.setText("Complemento:");
        getContentPane().add(jLabelComplemento);
        jLabelComplemento.setBounds(10, 440, 90, 30);

        jLabelCidade.setText("Cidade:");
        getContentPane().add(jLabelCidade);
        jLabelCidade.setBounds(10, 480, 70, 30);

        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCidade);
        jTextFieldCidade.setBounds(60, 480, 210, 30);

        jTextFieldComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(90, 440, 300, 30);

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(70, 400, 210, 30);

        jLabelCEP.setText("CEP:");
        getContentPane().add(jLabelCEP);
        jLabelCEP.setBounds(280, 480, 60, 30);

        jTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCEP);
        jTextFieldCEP.setBounds(310, 480, 80, 30);

        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero);
        jTextFieldNumero.setBounds(340, 400, 50, 30);

        jLabelNumero.setText("Número:");
        getContentPane().add(jLabelNumero);
        jLabelNumero.setBounds(290, 400, 60, 30);

        jLabelBairro.setText("Bairro:");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(10, 520, 40, 30);

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBairro);
        jTextFieldBairro.setBounds(60, 520, 250, 30);

        jTextFieldUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUF);
        jTextFieldUF.setBounds(360, 520, 30, 30);

        jLabelUF.setText("UF:");
        getContentPane().add(jLabelUF);
        jLabelUF.setBounds(330, 520, 60, 30);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 570, 400, 20);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 560, 400, 30);

        jToggleButtonVoltar.setText("Voltar");
        jToggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonVoltar);
        jToggleButtonVoltar.setBounds(10, 600, 100, 40);

        jToggleButtonSalvar.setText("Salvar");
        jToggleButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonSalvar);
        jToggleButtonSalvar.setBounds(280, 600, 100, 40);

        setSize(new java.awt.Dimension(416, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataAluActionPerformed

    private void jTextFieldNomeAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeAluActionPerformed

    private void jTextFieldTelefoneAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneAluActionPerformed

    private void jTextFieldCPFAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFAluActionPerformed

    private void jTextFieldNomeRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeRespActionPerformed

    private void jTextFieldTelefoneRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneRespActionPerformed

    private void jTextFieldDataRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataRespActionPerformed

    private void jTextFieldCPFRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFRespActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementoActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUFActionPerformed

    private void jToggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarActionPerformed
        TelaAlunos tela = new TelaAlunos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonVoltarActionPerformed

    private void jToggleButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSalvarActionPerformed
        TelaAlunos tela = new TelaAlunos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlunoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlunoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlunoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlunoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlunoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAdicionarResp;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPFAlu;
    private javax.swing.JLabel jLabelCPFResp;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelDataAlu;
    private javax.swing.JLabel jLabelDataResp;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNomeAlu;
    private javax.swing.JLabel jLabelNomeResp;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelTelefoneAlu;
    private javax.swing.JLabel jLabelTelefoneResp;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPFAlu;
    private javax.swing.JTextField jTextFieldCPFResp;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldDataAlu;
    private javax.swing.JTextField jTextFieldDataResp;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeAlu;
    private javax.swing.JTextField jTextFieldNomeResp;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldTelefoneAlu;
    private javax.swing.JTextField jTextFieldTelefoneResp;
    private javax.swing.JTextField jTextFieldUF;
    private javax.swing.JToggleButton jToggleButtonSalvar;
    private javax.swing.JToggleButton jToggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
