/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Faculdade
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonTurmas = new javax.swing.JToggleButton();
        jToggleButtonAlunos = new javax.swing.JToggleButton();
        jToggleButtonResp = new javax.swing.JToggleButton();
        jToggleButtonNovoUsuario = new javax.swing.JToggleButton();
        jToggleButtonVoltar = new javax.swing.JToggleButton();
        jToggleButtonFin = new javax.swing.JToggleButton();
        jToggleButtonCursos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jToggleButtonTurmas.setText("Turmas");
        jToggleButtonTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTurmasActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonTurmas);
        jToggleButtonTurmas.setBounds(330, 110, 110, 80);

        jToggleButtonAlunos.setText("Alunos");
        jToggleButtonAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonAlunos);
        jToggleButtonAlunos.setBounds(50, 110, 110, 80);

        jToggleButtonResp.setText("Responsáveis");
        jToggleButtonResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRespActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonResp);
        jToggleButtonResp.setBounds(190, 110, 110, 80);

        jToggleButtonNovoUsuario.setText("Novo Usuário");
        jToggleButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNovoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonNovoUsuario);
        jToggleButtonNovoUsuario.setBounds(330, 200, 110, 80);

        jToggleButtonVoltar.setText("Voltar");
        jToggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonVoltar);
        jToggleButtonVoltar.setBounds(190, 310, 100, 40);

        jToggleButtonFin.setText("Financeiro");
        jToggleButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFinActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonFin);
        jToggleButtonFin.setBounds(190, 200, 110, 80);

        jToggleButtonCursos.setText("Cursos");
        jToggleButtonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCursosActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonCursos);
        jToggleButtonCursos.setBounds(50, 200, 110, 80);

        setSize(new java.awt.Dimension(516, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonVoltarActionPerformed

    private void jToggleButtonAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAlunosActionPerformed
        TelaAlunos tela = new TelaAlunos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonAlunosActionPerformed

    private void jToggleButtonRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRespActionPerformed
        TelaResp tela = new TelaResp();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonRespActionPerformed

    private void jToggleButtonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCursosActionPerformed
TelasCursos tela = new TelasCursos();
        tela.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCursosActionPerformed

    private void jToggleButtonTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTurmasActionPerformed
TelaTurmas tela = new TelaTurmas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonTurmasActionPerformed

    private void jToggleButtonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFinActionPerformed
TelaFiananceiro tela = new TelaFiananceiro();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jToggleButtonFinActionPerformed

    private void jToggleButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNovoUsuarioActionPerformed
 TelaCadastroLogin tela = new TelaCadastroLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButtonAlunos;
    private javax.swing.JToggleButton jToggleButtonCursos;
    private javax.swing.JToggleButton jToggleButtonFin;
    private javax.swing.JToggleButton jToggleButtonNovoUsuario;
    private javax.swing.JToggleButton jToggleButtonResp;
    private javax.swing.JToggleButton jToggleButtonTurmas;
    private javax.swing.JToggleButton jToggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
