/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Faculdade
 */
public class TelaFiananceiro extends javax.swing.JFrame {

    /**
     * Creates new form TelaFiananceiro
     */
    public TelaFiananceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonVoltar = new javax.swing.JToggleButton();
        jToggleButtonContrato = new javax.swing.JToggleButton();
        jToggleButtonPag = new javax.swing.JToggleButton();
        jToggleButtonRelatorio = new javax.swing.JToggleButton();
        jToggleButtonInadimplentes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jToggleButtonVoltar.setText("Voltar");
        jToggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonVoltar);
        jToggleButtonVoltar.setBounds(190, 310, 100, 40);

        jToggleButtonContrato.setText("Contrato");
        jToggleButtonContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonContratoActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonContrato);
        jToggleButtonContrato.setBounds(50, 110, 110, 80);

        jToggleButtonPag.setText("Pagamento");
        jToggleButtonPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPagActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonPag);
        jToggleButtonPag.setBounds(190, 110, 110, 80);

        jToggleButtonRelatorio.setText("Relatório financeiro");
        jToggleButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonRelatorio);
        jToggleButtonRelatorio.setBounds(330, 110, 110, 80);

        jToggleButtonInadimplentes.setText("Inadimplentes");
        jToggleButtonInadimplentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonInadimplentesActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonInadimplentes);
        jToggleButtonInadimplentes.setBounds(50, 200, 110, 80);

        setSize(new java.awt.Dimension(516, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonVoltarActionPerformed

    private void jToggleButtonContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonContratoActionPerformed
        TelaAlunos tela = new TelaAlunos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonContratoActionPerformed

    private void jToggleButtonPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPagActionPerformed

    private void jToggleButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRelatorioActionPerformed
        TelaTurmas tela = new TelaTurmas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonRelatorioActionPerformed

    private void jToggleButtonInadimplentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonInadimplentesActionPerformed
        TelasCursos tela = new TelasCursos();
        tela.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonInadimplentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFiananceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFiananceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFiananceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFiananceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFiananceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButtonContrato;
    private javax.swing.JToggleButton jToggleButtonInadimplentes;
    private javax.swing.JToggleButton jToggleButtonPag;
    private javax.swing.JToggleButton jToggleButtonRelatorio;
    private javax.swing.JToggleButton jToggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
